# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: win1803

steps:
- powershell: ./build.ps1 -Target UpdateVersion
  displayName: 'Run a one-line script'

